# Generated by Django 5.1.1 on 2024-09-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_resumemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumemodel',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=100, null=True),
        ),
    ]
